import turtle
#Reio Viikmaa 07.10.24
#Harjutus 2
aken = turtle.Screen()
aken.setup(width = 500, height= 400)
aken.title("Sinilill - Reio")
turtle.speed("fastest")
turtle.pensize(10)

#õis
turtle.pencolor("green")
turtle.goto(0,-150)
turtle.lt(90)
turtle.fd(200)
turtle.lt(-90)
turtle.begin_fill()
turtle.color("blue", "lightblue")
turtle.circle(70)
turtle.lt(90)
turtle.end_fill()
#süda
turtle.begin_fill()
turtle.color("yellow", "yellow")
turtle.penup()
turtle.fd(45)
turtle.pendown()
turtle.rt(90)
turtle.circle(25)
turtle.end_fill()
#leht
turtle.penup()
turtle.goto(-20,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color("green", "green")
turtle.lt(90)
turtle.fd(40)
turtle.lt(120)
turtle.fd(40)
turtle.lt(120)
turtle.fd(40)
turtle.lt(120)
turtle.end_fill()

turtle.done()
